version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: github.com/iramarfalcao/book-db
    container_name: book-db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/books
    volumes:
      - books:/var/lib/postgresql/data

volumes:
  books: